// Fields
export const DNUMBER_FIELD_CODE = 'ZSt07qyq6Pt';
export const BIRTH_DATE_FIELD_CODE = 'NI0QRzJvQ0k';

// Programs
export const NEARKONTAKT_PROGRAM_CODE = 'DM9n1bUw8W8';
export const INDEKSERING_PROGRAM_CODE = 'uYjxkTbwRNf';
export const DUPLIKAT_PROGRAM_CODE = 'STKyXc3OT7i';
export const INNREISE_PROGRAM_CODE = 'B7gOGodZkcs';
export const DUPLICAT_INNREISE_PROGRAM_CODE = 'STKyXc3OT7i';

// Events
export const NAERKONTAKT_TESTRESULT_PROGRAM_STAGE_CODE = 'cMEGZf48YkC';
export const INDEKSERING_TESTRESULT_PROGRAM_STAGE_CODE = 'dDHkBd3X8Ce';
export const NAERKONTAKT_HELSESTATUS_PROGRAM_STAGE_CODE = 'mtYQyjaiLIU';
export const INDEKSERING_HELSESTATUS_PROGRAM_STAGE_CODE = 'oqsk2Jv4k3s';
export const INNREISEINFORMASJON_PROGRAM_STAGE_CODE = 'pQRu1RLcfLX';
export const OPPFOLGING_STAGE_CODE = 'htARRqRQNnz';
export const DUPLIKAT_OPPFOLGING_STAGE_CODE = 'ggzSsCfSnZh';
export const DUPLIKAT_INNREISE_STAGE_CODE = 'yfGvhpnZCxq'

// Entity types
export const INNREISE_ENTITY_TYPE = 'MCPQUTHX1Ze';