// Fields
export const DNUMBER_FIELD_ID = 'ZSt07qyq6Pt';
export const BIRTH_DATE_FIELD_ID = 'NI0QRzJvQ0k';

// Programs
export const NEARKONTAKT_PROGRAM_ID = 'DM9n1bUw8W8';
export const INDEKSERING_PROGRAM_ID = 'uYjxkTbwRNf';
export const DUPLIKAT_PROGRAM_ID = 'STKyXc3OT7i';
export const INNREISE_PROGRAM_ID = 'B7gOGodZkcs';

// Events
export const NAERKONTAKT_TESTRESULT_PROGRAM_STAGE_ID = 'cMEGZf48YkC';
export const INDEKSERING_TESTRESULT_PROGRAM_STAGE_ID = 'dDHkBd3X8Ce';
export const NAERKONTAKT_HELSESTATUS_PROGRAM_STAGE_ID = 'mtYQyjaiLIU';
export const INDEKSERING_HELSESTATUS_PROGRAM_STAGE_ID = 'oqsk2Jv4k3s';
export const INNREISEINFORMASJON_PROGRAM_STAGE_ID = 'pQRu1RLcfLX';
export const OPPFOLGING_STAGE_ID = 'htARRqRQNnz';
export const DUPLIKAT_OPPFOLGING_STAGE_ID = 'ggzSsCfSnZh';
export const DUPLIKAT_INNREISE_STAGE_ID = 'yfGvhpnZCxq';
export const NAERKONTAKT_OPPFOLGING_PROGRAM_STAGE_ID = 'sAV9jAajr8x';
// Entity types
export const INNREISE_ENTITY_TYPE = 'MCPQUTHX1Ze';

// Data elements
export const INNREISE_AVREISELAND_DATA_ELEMENT_ID = 'EwrMxsQG3OX';
export const INNREISE_OPPFOLGINGSTATUS_ID = 'uI17SVSOZmQ';
export const INNREISE_KARANTENE_ALTERNATIV_TEXT_ID = 'YMfxPPwVfOi';
export const INNREISE_KARANTENE_ALTERNATIV_CODE_ID = 'bllUT5vac3r';
export const INNREISE_UNNTAK_TYPE_TEXT_ID = 'woCg1rzHYkn';
export const INNREISE_UNNTAK_TYPE_CODE_ID = 'CoSw0VqJgn7';
export const INNREISE_KARANTENE_GJENOMFORING_TYPE_TEXT_ID = 'IWhH4IfCOX9';
export const INNREISE_KARANTENE_GJENOMFORING_TYPE_CODE_ID = 'fJcTMI7RD9u';
export const INNREISE_OPPHOLDSSTED_ID = 'LYrjfgwVNVn';
export const INNREISE_ARBEIDSGIVER_NAVN_ID = 'uncjwHvpOWP';

export const PROFIL_NASJONALT_FELLES_HJELPENUMMER = 'WBjHgYajTsb';
export const PROFIL_FNR = 'fkUN6jLp7K4';
export const PROFIL_FNR_AS_WELL = 'ZSt07qyq6Pt';
// Lookup IDs

export const COUNTRY_LOOKUP_ID = 'ynHtyLDVeJO';
export const STATUS_OPPFOLGNING_LOOKUP_ID = 'IDHxRNOGuSS';

// Attributes
export const INNREISE_OPPFOLGINGSTATUS_ATTRIBUTE_ID = 'fYNNIxUOddv';
export const INNREISE_KARANTENEKODE_2_ATTRIBUTE_ID = 'bjujLWjT1Eq';
export const INNREISE_KARANTENEKODE_4_ATTRIBUTE_ID = 'bJvyD0inEh0';
export const INNREISE_KARANTENETYPE_ATTRIBUTE_ID = 'XamASy7t0Jv';
export const INNREISE_INNREISE_DATO_ATTRIBUTE_ID = 'VpUtJW18CiY';
export const INNREISE_SISTE_PROVESVAR_DATO_ATTRIBUTE_ID = 'M3FtWmK8YEP';
export const INNREISE_SISTE_PROVESVAR_ATTRIBUTE_ID = 'CMF6k9jvOuU';
export const INNREISE_OPPHOLDSADRESSE_ATTRIBUTE_ID = 'DeHufwWNjmh';
export const INNREISE_ARBEIDSGIVER_ATTRIBUTE_ID = 'rGDv6a0AvWF';
export const INNREISE_AVREISELAND_ATTRIBUTE_ID = 'nv5gV7eM3u6';
export const PROFIL_FORETRUKKET_SPRAAK_ATTRIBUTE_ID = 'xTdN78uRiJm';
export const PROFIL_EPOST_ATTRIBUTE_ID = 'Ym6yIceP4RO';
export const PROFIL_MOBIL_TLF_ATTRIBUTE_ID = 'h1PoxEMqi9t';
export const PROFIL_FNR_ATTRIBUTE_ID = 'NI0QRzJvQ0k';